### PR TITLE
game data structure changes + bug fixes and minor feature work

### LINKED ISSUE #120: Improve puzzle export
No need to have a separate pop-up to choose the target website

### LINKED ISSUE #121: On puzzle completion allow the user to export an LMD solution code
Provide text box for entry of code description, say R1;C2, and the appropriate 18 digit string will be copied to the clipboard ready to be pasted straight into LMD

### LINKED ISSUE #123: Incorrect digits being filled in by autoscanner
While creating the walkthrough for Killoc4tor: Kill List the autoscanner was filling in unearned digits. some issue with the combination of killer cages and cornermarks?

### LINKED ISSUE #129: Game locks up when redoing with nothing to redo
Clicking Redo on a puzzle with no undone steps causes the puzzle to lock up

### PR DESCRIPTION
**Pull request by starwarigami**
This provides the foundation for other features to be pulled in at a later date, and improves memory usage during gameplay

- Closes #129
- Closes #123
- Closes #121
- Closes #120

### CODE REVIEW

File: apps/website/src/routes/sudoku/editor/+page.svelte [hunk 1]
```diff
@@ -75,21 +81,24 @@
...
       if (walkthrough.length) {
-        const finalStep = walkthrough[walkthrough.length - 1].step;
+        const finalStep = walkthrough[walkthrough.length - 1].gameData;
         if (
-          userInputs.values.some((row, i) => {
-            return row.some((value, j) => {
-              return value === '' && finalStep.values[i][j] !== '';
+          gameData.cellValues.some((row, i) => {
+            return row.some((cell, j) => {
+              return !cell.digits && finalStep.cellValues[i][j].digits;
```
Comment (SorenHolstHansen) [inline apps/website/src/routes/sudoku/editor/+page.svelte:90]:
```suggestion
              return cell.digits !== "" && finalStep.cellValues[i][j].digits;
```
Or what is meant here

File: apps/website/src/routes/sudoku/editor/+page.svelte [hunk 2]
```diff
@@ -264,20 +280,43 @@
...
+        </button>
+        <button
+          on:click={() => exportPuzzle(clues, gameData, sudokuTitle, description, 'CTC')}
+          class="w-8 h-8"
+          title="Export to CtC"
+        >
+          <CtC />
+        </button>
+      </div>
+    </details>
```
Comment (SorenHolstHansen) [inline apps/website/src/routes/sudoku/editor/+page.svelte:319]: Is this the same as in the other page? If so, can we pull it out into its own component?

File: apps/website/src/routes/sudoku/editor/+page.svelte [hunk 3]
```diff
@@ -286,15 +325,37 @@
...
```
Comment (SorenHolstHansen) [inline apps/website/src/routes/sudoku/editor/+page.svelte:358]: The same with this

File: packages/icons/src/lib/icons/CtC.svelte [hunk 4]
```diff
@@ -1,78 +1,344 @@
-<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 256 256">
```
Comment (SorenHolstHansen) [inline packages/icons/src/lib/icons/CtC.svelte:1]: Just for my interest: Have they changed icon?

File: packages/icons/src/lib/icons/FPuzzles.svelte [hunk 5]
```diff
@@ -1,10 +1,20 @@
-<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 256 256">
+<svg viewBox="0 0 256 256" fill="#000000" xmlns="http://www.w3.org/2000/svg">
+  <defs>
+    <style bx:fonts="Bungee">
+      @import url(https://fonts.googleapis.com/css2?family=Bungee%3Aital%2Cwght%400%2C400&amp;display=swap);
+    </style>
+  </defs>
```
Comment (SorenHolstHansen) [inline packages/icons/src/lib/icons/FPuzzles.svelte:6]: Is this needed? fonts are very heavy to import, so would hope we could remove this.

If not, take a look at [this](https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests) which can optimize it

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte [hunk 6]
```diff
@@ -1,32 +1,31 @@
...
-        >
-          {centermark}
-        </text>
-      {/if}
+{#if cellValues}
+  <g id="centermarks" class="pointer-events-none">
+    {#each cellValues as cells, row}
+      {#each cells as cell, column}
+        {@const centermarks = cell.centermarks}
+        {#if centermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte:14]: Prefer checking equality and inequality with null, as both undefined and null is == null, but only undefined is === undefined
```suggestion
        {#if centermarks != null && givens[row][column] === '' && cell.digits == null}
```

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte [hunk 7]
```diff
@@ -51,17 +64,15 @@
...
         />
       {/if}
-      {#if gameColor && gameColor.length > 0}
-        <defs>
-          <clipPath id="square-{row}-{column}" clipPathUnits="userSpaceOnUse">
-            <rect x={CELL_SIZE * column} y={CELL_SIZE * row} width={CELL_SIZE} height={CELL_SIZE} />
-          </clipPath>
-        </defs>
-        {#each gameColor as color, i}
+      {#if gameColors !== undefined}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte:67]:
```suggestion
      {#if gameColors != null}
```

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte [hunk 8]
```diff
@@ -1,33 +1,52 @@
...
-            {cornerMark}
-          </text>
-        {/each}
-      {/if}
+{#if cellValues}
+  <g id="cornermarks" class="pointer-events-none">
+    {#each cellValues as cells, row}
+      {#each cells as cell, column}
+        {@const cornermarks = cell.cornermarks}
+        {#if cornermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:30]:
```suggestion
        {#if cornermarks != null && givens[row][column] === '' && cell.digits == null}
```

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte [hunk 9]
```diff
@@ -1,33 +1,52 @@
...
+          {@const n = cornermarks.length}
+          {#each cornermarks as cornerMark, i}
+            {#if i < 8}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:33]: What is this for? Are we ignoring cornermarks if there are too many?

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte [hunk 10]
```diff
@@ -1,33 +1,52 @@
...
+              {@const k = getPosition(n, i)}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:34]: It would be nice with some more descriptive names than n, i and k

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte [hunk 11]
```diff
@@ -1,33 +1,52 @@
...
+      } else if (i >= 4) {
+        if (n === 7) {
+          k += 2;
+        } else {
+          k += 1;
+        }
+      }
+    }
+    return k;
+  }
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:22]: I have no clue what this does ;) Can you put some comments in?

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte [hunk 12]
```diff
@@ -24,18 +21,21 @@
...
-  {#each arrayfrom0ToN(dimensions.rows) as row}
-    {#each arrayfrom0ToN(dimensions.columns) as column}
-      {@const val = givens[row][column] || values?.[row]?.[column]}
-      {#if val && val.length > 0}
+  {#each givens as givenDigits, row}
+    {#each givenDigits as given, column}
+      {@const isGiven = given !== ''}
+      {@const cell = cellValues?.[row]?.[column]}
+      {@const digits = isGiven ? [given] : cell?.digits}
+      {#if digits !== undefined}
```
Comment (SorenHolstHansen) [inline packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte:29]:
```suggestion
      {#if digits != null}
```

File: packages/sudoku-editor/src/lib/sudokuStore/index.ts [hunk 13]
```diff
@@ -101,15 +101,15 @@ function createEditorHistoryStore() {
...
-    }
+  function getClue<T extends keyof EditorHistoryStep>(type: T): Readable<EditorHistoryStep[T]> {
+    return derived([history, step], ([$editorHistory, $editorStep]) => {
+      const res = $editorHistory[$editorStep]?.[type];
+      if (typeof res === 'number') {
+        return $editorHistory[res]?.[type] as EditorHistoryStep[T];
+      } else {
+        return res as EditorHistoryStep[T];
+      }
+    });
```
Comment (SorenHolstHansen) [inline packages/sudoku-editor/src/lib/sudokuStore/index.ts:112]: Niiice!

File: packages/sudoku-game/src/lib/Game/Controller/components/CenterMarks.svelte [hunk 14]
```diff
@@ -2,59 +2,66 @@
...
+      );
       if (clearAllGameCells) {
         // completely clear the selected cells
         gameHistory.clearCells(positions);
         return;
       } else {
         // Remove the center marks from all selected cells
         positions.forEach((p) => {
-          newCentermarks[p.row][p.column] = '';
+          delete newCellValues[p.row][p.column].centermarks;
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/CenterMarks.svelte:30]: Is there another solution than deleting here, I don't like the potential side effects (as explained in [this](https://eslint.org/docs/latest/rules/no-delete-var))

File: packages/sudoku-game/src/lib/Game/Controller/components/CornerMarks.svelte [hunk 15]
```diff
@@ -2,60 +2,67 @@
...
+      );
       if (clearAllGameCells) {
         // completely clear the selected cells
         gameHistory.clearCells(positions);
         return;
       } else {
         // Remove the center marks from all selected cells
         positions.forEach((p) => {
-          newCornermarks[p.row][p.column] = '';
+          delete newCellValues[p.row][p.column].cornermarks;
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/CornerMarks.svelte:31]: Same here

File: packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte [hunk 16]
```diff
@@ -21,53 +21,52 @@
...
+    if (newColor === undefined) {
+      const clearAllGameCells = positions.every((p) => !currentCellValues[p.row][p.column].colors);
+      if (clearAllGameCells) {
+        // completely clear the selected cells
+        gameHistory.clearCells(positions);
+        return;
+      } else {
+        // Remove the colors from all selected cells
+        positions.forEach((p) => {
+          delete newCellValues[p.row][p.column].colors;
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte:35]: And here

File: packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte [hunk 17]
```diff
@@ -21,53 +21,52 @@
...
-    // Check if we should clear all game cells
-    const clearAllGameCells =
-      newColor == null && positions.every((p) => currentColors[p.row]?.[p.column] == null);
-    if (clearAllGameCells) {
-      // clear all the cells in the game
-      gameHistory.clearCells(positions);
+    const currentCellValues = get(gameHistory.getValue('cellValues'));
+    const newCellValues = deepCopy(currentCellValues);
+    if (newColor === undefined) {
+      const clearAllGameCells = positions.every((p) => !currentCellValues[p.row][p.column].colors);
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte:27]:
```suggestion
      const clearAllGameCells = positions.every((p) => currentCellValues[p.row][p.column].colors !== "");
```

File: packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte [hunk 18]
```diff
@@ -21,53 +21,52 @@
...
+      if (!allCellsHasColor) {
+        // Add it to the cells that does not have it
+        positions.forEach((p) => {
+          const colors = currentCellValues[p.row][p.column].colors;
+          if (colors) {
+            if (!colors.includes(newColor)) {
+              newCellValues[p.row][p.column].colors = [...colors, newColor]
+                .map((c) => Colors.indexOf(c))
+                .sort()
+                .map((n) => Colors[n]);
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte:51]: Something like this would be better i think. Not sure if it should be this, or the other way round, i.e. `Colors.indexOf(b) - Colors.indexOf(a)`
```suggestion
                .sort((a, b) => Colors.indexOf(a) - Colors.indexOf(b))
```

File: packages/sudoku-game/src/lib/Game/Controller/components/Numbers.svelte [hunk 19]
```diff
@@ -1,67 +1,73 @@
...
-          if (newValues[position.row][position.column] === newValue) {
-            newValues[position.row][position.column] = '';
-            anyChanges = true;
-          } else {
-            // Insert the number
-            newValues[position.row][position.column] = newValue;
-            newCentermarks[position.row][position.column] = '';
-            newCornermarks[position.row][position.column] = '';
+              delete newCellValues[p.row][p.column].centermarks;
+              delete newCellValues[p.row][p.column].cornermarks;
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/Game/Controller/components/Numbers.svelte:51]: And here

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts [hunk 20]
```diff
@@ -553,41 +528,48 @@ function createScannerStore() {
...
+      if (
+        !getCornerSets(cell, false)
+          .filter((s) => s.cells.length === 1)
+          .some((s) => {
+            if (newCandidateValues.includes(s.digit)) {
+              newCandidateValues = [s.digit];
+              return true;
+            }
+            return false;
+          })
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/sudokuStore/scanner.ts:543]: Move this out into a constant outside the if-statement and give it a descriptive name

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts [hunk 21]
```diff
@@ -744,91 +724,79 @@ function createScannerStore() {
...
+					//find the set of cornermarks that this cell is part of
+					getCornerSets(cell, false).forEach((s) => {
+						if (digits?.includes(s.digit)) {
+							//remove all cornermarks that match the placed digit
+							s.cells.forEach((c) => {
+								delete newCellValues[c.row][c.column].cornermarks;
+							});
+						}
+					});
+				}*/
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/sudokuStore/scanner.ts:789]: Delete this?

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts [hunk 22]
```diff
@@ -949,6 +917,7 @@ function createScannerStore() {
     startScan,
     stopScan,
     isScanning,
+    getSeenCells,
     getHighlightedCells,
     toggleSeen,
     toggleTuples,
```
Comment (SorenHolstHansen) [inline packages/sudoku-game/src/lib/sudokuStore/scanner.ts:923]: Not a comment on this line, but is there anyway this store can be simplified? I would have no clue how to even begin if I had to fix anything here ;)

Perhaps pull something out into util functions, or something?

File: packages/utils/src/utils/getValuesFromRange.ts [hunk 23]
```diff
@@ -0,0 +1,23 @@
+export function getValuesFromRange(range: string): string[] {
```
Comment (SorenHolstHansen) [inline packages/utils/src/utils/getValuesFromRange.ts:1]: Add a comment to this function to document what its purpose is

File: packages/utils/src/utils/getValuesFromRange.ts [hunk 24]
```diff
@@ -0,0 +1,23 @@
...
+    if (values[n] === '-') {
+      const range: string[] = [];
+      if (n > 0 && n < values.length - 1) {
+        const start = values[n - 1].charCodeAt(0);
+        const end = values[n + 1].charCodeAt(0);
+        let char = start + 1;
+        while (char < end) {
+          range.push(String.fromCharCode(char));
+          ++char;
+        }
```
Comment (SorenHolstHansen) [inline packages/utils/src/utils/getValuesFromRange.ts:17]: What does this do? And is it possible to do it without char-codes? Feels like magic

**Review by SorenHolstHansen — CHANGES_REQUESTED** [review]
Overall this is really great!

I have a few comments here and there, and the preview is failing, so will wait for that to go through so I can look at it live.

But other than that, this is really great!

File: apps/website/prisma/seed.ts [hunk 25]
```diff
@@ -279,7 +279,6 @@ const main = async (): Promise<void> => {
         'Normal sudoku rules apply: Fill each row, column and marked 3x3 box with the numbers 1 to 9 so that no number appears twice.',
       points: 0,
       rank: 0,
-      difficulty: 4,
```
[the remark this answers is not in the document]
Comment (starwarigami) [reply apps/website/prisma/seed.ts:282]: I updated the puzzle constraints to use the prefabs so that the constraint validation in the upcoming PR can be tested

File: apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts [hunk 26]
```diff
@@ -61,12 +68,12 @@ export function exportAsFPuzzlesJson(
...
-    antiknight: flags.includes('Antiknight') || undefined,
+    antiking: flags.includes('Antiking') ? true : undefined,
+    antiknight: flags.includes('Antiknight') ? true : undefined,
     //author: string,
-    'diagonal+': flags.includes('DiagonalPos') || undefined,
-    'diagonal-': flags.includes('DiagonalNeg') || undefined,
-    disjointgroups: flags.includes('DisjointSets') || undefined,
+    'diagonal+': flags.includes('DiagonalPos') ? true : undefined,
+    'diagonal-': flags.includes('DiagonalNeg') ? true : undefined,
+    disjointgroups: flags.includes('DisjointSets') ? true : undefined,
```
[the remark this answers is not in the document]
Comment (starwarigami) [reply apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts:76]: Merge issue

File: apps/website/src/routes/sudoku/editor/+page.svelte [hunk 27]
```diff
@@ -42,9 +43,15 @@
...
-  let userInputs: GameHistoryStep = {
-    ...defaultUserInputs(data.sudoku?.dimensions),
-    values: data.sudoku?.solution?.numbers ?? defaultValues(data.sudoku?.dimensions)
+  let gameData: GameHistoryStep = {
+    ...defaultGameData(data.sudoku?.dimensions),
+    cellValues:
+      data.sudoku?.solution?.numbers.map((row) =>
+        row.map((value) => {
+          const digits = value.split('');
+          return digits.length ? { digits: digits.map((d) => d as Digit) } : {};
```
[the remark this answers is not in the document]
Comment (starwarigami) [reply apps/website/src/routes/sudoku/editor/+page.svelte:52]: Done - wasn't aware this was an option

File: apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts (hunk 26 above)
[the remark this answers is not in the document]
Comment (starwarigami) [reply apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts:76]: This was not an intentional change, rather a merge issue where we both fixed the indexOf('<FLAGNAME>') == -1 inefficiency independently and I merged my changes on top of yours for ease of solving the file merge

File: apps/website/src/routes/sudoku/[id]/+page.svelte [hunk 28]
```diff
@@ -98,23 +103,38 @@
...
+      </button>
+      <button
+        on:click={() => exportPuzzle(clues, gameData, sudokuTitle, description, 'CTC')}
+        class="w-8 h-8"
+        title="Export to CtC"
+      >
+        <CtC />
+      </button>
+    </div>
+  </details>
```
[the remark this answers is not in the document]
Comment (starwarigami) [reply apps/website/src/routes/sudoku/[id]/+page.svelte:136]: I'll send you a screenshot

File: packages/utils/src/utils/getValuesFromRange.ts (hunk 24 above)
Comment (starwarigami) [reply packages/utils/src/utils/getValuesFromRange.ts:17]: Comment added to function

//Converts a string of the form "1-9" into an array of all chars in the range, e.g. [1,2,3,4,5,6,7,8,9]
//Can handle multiple different ranges in a single, separated by ";", "," or " "
//e.g. "0-3; A,B,C X-Z" -> [0,1,2,3,A,B,C,X,Y,Z]

The function is building a range of characters, so incrementing the char code seemed like the obvious way to approach it

File: packages/icons/src/lib/icons/CtC.svelte (hunk 4 above)
Comment (starwarigami) [reply packages/icons/src/lib/icons/CtC.svelte:1]: No, but we were not using the CtC icon up to this point. I had put a placeholder in that was the closest phospor icon that resembled theirs, but I finally tracked down an image I could convert into a usable svg of the genuine article

File: packages/icons/src/lib/icons/FPuzzles.svelte (hunk 5 above)
Comment (starwarigami) [reply packages/icons/src/lib/icons/FPuzzles.svelte:6]: Not needed in the slightest. I just wanted to add an F into the puzzle piece for clarity, since f-puzzles doesn't have an icon of its own

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte (hunk 6 above)
Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte:14]: but neither cell.centremarks or cell.digits can ever be null, so why would I need to check for it?

export const CellDataValidator = z.object({
  digits: z.array(DigitValidator).optional(),
  centermarks: z.array(DigitValidator).optional(),
  cornermarks: z.array(DigitValidator).optional(),
  colors: z.array(ColorValidator).optional()
});

They are defined as optional, not nullish - is that a problem?

File: packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte (hunk 18 above)
Comment (starwarigami) [reply packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte:51]: good idea

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte (hunk 11 above)
Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:22]: Will do.

FYI, It spaces the corner marks out for clarity so they don't interfere with the centremarks. For up to 3 cornermarks it uses the top row, for up to 6 it uses the top and bottom rows, and for 7 or 8 it uses the left and right of the middle row. If you're using all 9 digits as cornermarks then you're solving the puzzle wrong!

Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:22]: Done

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte (hunk 7 above)
Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte:67]: The fields of CellData object can never be null so seems unnecessary to check for it?

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte (hunk 8 above)
Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:30]: The fields of CellData object can never be null so seems unnecessary to check for it?

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte (hunk 12 above)
Comment (starwarigami) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte:29]: The fields of CellData object can never be null so seems unnecessary to check for it?

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts (hunk 22 above)
Comment (starwarigami) [reply packages/sudoku-game/src/lib/sudokuStore/scanner.ts:923]: MIght be safer to do this in another branch?

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts (hunk 21 above)
Comment (starwarigami) [reply packages/sudoku-game/src/lib/sudokuStore/scanner.ts:789]: I fell like it's there to remind me of something? I don't remember what...

File: packages/icons/src/lib/icons/FPuzzles.svelte (hunk 5 above)
Comment (SorenHolstHansen) [reply packages/icons/src/lib/icons/FPuzzles.svelte:6]: Try it without the font then, don't want a whole font being loaded in

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte (hunk 6 above)
Comment (SorenHolstHansen) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte:14]: No, not a problem. Checking against null instead of undefined is just preferred as you then catch all "nullishness" instead of just undefinedness.

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte (hunk 7 above)
Comment (SorenHolstHansen) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte:67]: See above comment

File: packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte (hunk 9 above)
Comment (SorenHolstHansen) [reply packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte:29]: Yeah alright, but a bit weird to just not show cornermarks if the user has added them, but I guess it works

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts (hunk 22 above)
Comment (SorenHolstHansen) [reply packages/sudoku-game/src/lib/sudokuStore/scanner.ts:923]: Yeah, agree

File: packages/utils/src/utils/getValuesFromRange.ts (hunk 24 above)
Comment (SorenHolstHansen) [reply packages/utils/src/utils/getValuesFromRange.ts:20]: Aaarh, right, the comments made it much clearer, thanks

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts (hunk 21 above)
Comment (starwarigami) [reply packages/sudoku-game/src/lib/sudokuStore/scanner.ts:789]: I can deal with this in the future branch where I refactor the scanner code. I think it's something important that I need to get working, but I'll need to delve into it properly to figure out what I was trying to do and why I commented it out

File: packages/icons/src/lib/icons/FPuzzles.svelte (hunk 5 above)
Comment (starwarigami) [reply packages/icons/src/lib/icons/FPuzzles.svelte]: Font removed - I draw the F with a polygon now

File: packages/sudoku-game/src/lib/sudokuStore/scanner.ts (hunk 21 above)
Comment (SorenHolstHansen) [reply packages/sudoku-game/src/lib/sudokuStore/scanner.ts:789]: Cool, no problem then

**Review by SorenHolstHansen — APPROVED** [review]
